# Generated by Django 5.0.4 on 2025-05-07 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
