# Generated by Django 5.0.4 on 2025-05-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
