# Generated by Django 5.0.4 on 2025-05-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_news_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
