# Generated by Django 5.0.4 on 2025-05-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_category_conservationactivity_conservationmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
    ]
